services:
  - type: web
    name: esi-tickets
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    disk:
      name: esi-tickets-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
